#!/usr/bin/env bash

function runDocker
{
    local -r dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

    local -r applicationName=$(cat "${dir}/projectName");

    local -r hostIp="$(docker network inspect bridge --format '{{ (index .IPAM.Config 0).Gateway }}')"

    if [[ $# -eq 0 ]]; then
        docker run --rm -v $(pwd):/home/app/src -e "XDEBUG_REMOTE_HOST=${hostIp}" -e "PHP_IDE_CONFIG=serverName=${applicationName}" -it "${applicationName}" "sh"
    else
        docker run --rm -v $(pwd):/home/app/src -e "XDEBUG_REMOTE_HOST=${hostIp}" -e "PHP_IDE_CONFIG=serverName=${applicationName}" -i "${applicationName}" "$@"
    fi
}

runDocker "$@"
