<?php

declare(strict_types=1);

namespace Robier\EmailNormalization\Provider;

use Robier\EmailNormalization\DomainProvider;
use Robier\EmailNormalization\Feature;

#[Feature\LowercaseName]
#[Feature\TagAddressing('+')]
final class Microsoft implements DomainProvider
{
    public function domains(): array
    {
        return [
            'hotmail.com',
            'hotmail.at',
            'hotmail.be',
            'hotmail.ca',
            'hotmail.cl',
            'hotmail.co.il',
            'hotmail.co.nz',
            'hotmail.co.th',
            'hotmail.co.uk',
            'hotmail.com.ar',
            'hotmail.com.au',
            'hotmail.com.br',
            'hotmail.com.gr',
            'hotmail.com.mx',
            'hotmail.com.pe',
            'hotmail.com.tr',
            'hotmail.com.vn',
            'hotmail.cz',
            'hotmail.de',
            'hotmail.dk',
            'hotmail.es',
            'hotmail.fr',
            'hotmail.hu',
            'hotmail.id',
            'hotmail.ie',
            'hotmail.in',
            'hotmail.it',
            'hotmail.jp',
            'hotmail.kr',
            'hotmail.lv',
            'hotmail.my',
            'hotmail.ph',
            'hotmail.pt',
            'hotmail.sa',
            'hotmail.sg',
            'hotmail.sk',
            'live.com',
            'live.be',
            'live.co.uk',
            'live.com.ar',
            'live.com.mx',
            'live.de',
            'live.es',
            'live.eu',
            'live.fr',
            'live.it',
            'live.nl',
            'msn.com',
            'outlook.com',
            'outlook.at',
            'outlook.be',
            'outlook.cl',
            'outlook.co.il',
            'outlook.co.nz',
            'outlook.co.th',
            'outlook.com.ar',
            'outlook.com.au',
            'outlook.com.br',
            'outlook.com.gr',
            'outlook.com.pe',
            'outlook.com.tr',
            'outlook.com.vn',
            'outlook.cz',
            'outlook.de',
            'outlook.dk',
            'outlook.es',
            'outlook.fr',
            'outlook.hu',
            'outlook.id',
            'outlook.ie',
            'outlook.in',
            'outlook.it',
            'outlook.jp',
            'outlook.kr',
            'outlook.lv',
            'outlook.my',
            'outlook.ph',
            'outlook.pt',
            'outlook.sa',
            'outlook.sg',
            'outlook.sk',
            'passport.com',
        ];
    }
}
